# Book settings
title: Introduction to Python for Geographic Data Analysis
author: Henrikki Tenkanen, Vuokko Heikinheimo & Dave Whipp
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex
